### ISSUE TITLE
support greenplum(kernel pg9.4)?

### ISSUE THREAD

**Issue by wonb168** [RhodiumToad/pllua-ng#18]
pg versions 9.5, 9.6, 10, 11, 12 and 13.
not support greenplum(kernel pg9.4)?

**Comment by RhodiumToad** [comment]
Correct memory management requires using features (memory context callbacks) that were added to pg in version 9.5, so support for earlier versions is not possible. I'm not personally familiar with greenplum. (Incorrect memory management in the original implementation was the main reason for this rewrite.)
