### ISSUE TITLE
connection shared 

### ISSUE THREAD

**Issue by golgote** [RhodiumToad/pllua-ng#3]
Hi, I was wondering if there was a way to share a lua variable globally accross sessions.
If I use _G, it seems to be only available for the current session. My use case is for loading large hunspell dictionaries for luahunspell, so it creates some overhead if it has to be done on every connections. Ex: 

```lua
-- CREATE OR REPLACE FUNCTION tokenize_spell(contents text) RETURNS text LANGUAGE plluau IMMUTABLE AS $$
if not _G.spellfr then
   local spell = require 'hunspell'
   local spellfr = spell.new('fr_FR.affix', 'fr_FR.dict')
   _G.spell = spellfr
end
-- ...
```
Thanks for all your work on the new PLLua, it is much cleaner 😄

**Comment by RhodiumToad** [comment]
Each connection is actually a separate process, so sharing data between connections is a rather tricky business.

If the data is actually static, and you're not using Windows, then it is possible to arrange to preload the data once in the postmaster process and have every connection inherit the preloaded copy; this is the main reason why all of those on_init configuration settings exist.

The basic idea is to write your initialization code in the form of a require-able module and set pllua.on_init = "require 'mymodule'" and shared_preload_libraries="pllua" in postgresql.conf. This will cause one (by default) Lua state to be created in the postmaster process when postgresql is started or restarted, and the on_init string will be executed in that state. Then, every new connection will inherit that state via fork(), and the first time that the connection would normally create a fresh state, it'll use the pre-initialized one instead.
