### ISSUE TITLE
Get $SHAREDIR from pllua code

### ISSUE THREAD

**Issue by golgote** [RhodiumToad/pllua-ng#4]
Hi,
I was wondering if there was a way to know what the sharedir is, from inside a pllua script, something that would return the equivalent of `pg_config --sharedir`?
Thank you

**Comment by golgote** [comment]
Also, I need this in the pllua.on_init step, so without database access 😬

**Comment by RhodiumToad** [comment]
Hm, that's a good question. The answer is that there currently is no good way even _with_ database access; the server's get_share_path() function seems not to be exposed to SQL anywhere.

I suppose I could add this functionality, either by storing values into the state initially or providing a require-able module for it.

**Comment by RhodiumToad** [comment]
(require "pllua.paths").share()

That's in the master branch of this repo, it'll be in the master branch of the pllua/pllua-ng repo later once testing is done. A release may follow once I've cleared out any other pending work.
