### ISSUE TITLE
timestamp access methods

### ISSUE THREAD

**Issue by RhodiumToad** [RhodiumToad/pllua-ng#7]
Add :to_epoch, :to_epoch_ms and so on for timestamp types?

**Comment by bjne** [comment]
Perhaps rounding is up to lua, and one only exposes :epoch as a float?

**Comment by RhodiumToad** [comment]
So what I'm looking at is this:

Firstly, field access to a date/time datum using the field names used by extract(), e.g. `t.year` or `t.epoch` (this returns a float); as extensions, `t.epoch_msec` and `t.epoch_usec` work too. 

Secondly, returning/constructing date/time values by passing a Lua table as with `os.time`, but allowing extensions such as `{ epoch_msec = blah }`

Just need to write a whole lot of tests...
